name: Deploy Project01 Static Site to S3 + CloudFront

on:
  push:
    branches:
      - main
    paths:
      - "Project01-static-site/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync site to S3
        run: |
          aws s3 sync Project01-static-site s3://neel-cloud-engineering-portfolio-project01 --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E19LHMXP03G7EQ \
            --paths "/*"
